#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
board.py — собирает табло прогресса из комментариев в issue.

Ученик отправляет результат через `check.sh --submit`, скрипт оставляет
комментарий с невидимым маркером:

    <!-- hs:lesson=01-terminal;track=level-0;pass=8;total=8;lang=ru;user=Ann;ts=... -->

Workflow вызывает этот модуль: `add` разбирает маркер и дописывает запись,
`render` пересобирает board/board.md, `sync-issue` обновляет тело issue.

Запуск вручную:
    python3 tools/board.py add --body "$(cat comment.txt)"
    python3 tools/board.py render
    python3 tools/board.py show
"""

import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "board", "data.json")
BOARD_MD = os.path.join(ROOT, "board", "board.md")
ISSUE_BODY = os.path.join(ROOT, "board", "issue-body.md")

MARKER = re.compile(r"<!--\s*hs:(.*?)\s*-->", re.S)

LESSON_TITLES = {
    "01-terminal": "Lesson 1. Terminal and navigation",
    "02-files-and-permissions": "Lesson 2. Files and permissions",
    "03-git-basics": "Lesson 3. Git from scratch",
    "04-first-script": "Lesson 4. Your first script",
}

TRACKS = {"level-0": ["01-terminal", "02-files-and-permissions",
                      "03-git-basics", "04-first-script"]}


def load():
    if not os.path.exists(DATA):
        return []
    with open(DATA, encoding="utf-8") as f:
        return json.load(f)


def save(records):
    os.makedirs(os.path.dirname(DATA), exist_ok=True)
    records.sort(key=lambda r: r.get("ts", ""))
    with open(DATA, "w", encoding="utf-8") as f:
        json.dump(records, f, ensure_ascii=False, indent=2)
        f.write("\n")


def parse_marker(body):
    """Достаёт запись из маркера. None — если маркера нет или он битый."""
    if not body:
        return None
    m = MARKER.search(body)
    if not m:
        return None
    fields = {}
    for part in m.group(1).split(";"):
        if "=" not in part:
            continue
        k, v = part.split("=", 1)
        fields[k.strip()] = v.strip()
    if not {"lesson", "pass", "total"} <= set(fields):
        return None
    try:
        rec = {
            "lesson": fields["lesson"],
            "track": fields.get("track", "level-0"),
            "pass": int(fields["pass"]),
            "total": int(fields["total"]),
            "lang": fields.get("lang", "ru"),
            "user": fields.get("user", "unknown"),
            "ts": fields.get("ts", ""),
        }
    except ValueError:
        return None
    if rec["pass"] > rec["total"] or rec["total"] <= 0:
        return None
    return rec


def add(rec):
    """Одна запись на (user, lesson) — последняя побеждает."""
    if rec is None:
        print("маркер не найден — комментарий пропущен")
        return False
    records = load()
    records = [r for r in records
               if not (r["user"] == rec["user"] and r["lesson"] == rec["lesson"])]
    records.append(rec)
    save(records)
    print("добавлено: %s %s %d/%d" % (rec["user"], rec["lesson"],
                                       rec["pass"], rec["total"]))
    return True


def passed(records, track, lesson):
    """Множество пользователей, закрывших урок полностью."""
    return {r["user"] for r in records
            if r["track"] == track and r["lesson"] == lesson
            and r["pass"] == r["total"]}


def bar(done, total_steps):
    if total_steps == 0:
        return ""
    filled = int(round(done / total_steps * 10))
    filled = max(0, min(10, filled))
    return "█" * filled + "░" * (10 - filled)


def render(with_title=True):
    records = load()
    users = sorted({r["user"] for r in records})

    out = []
    if with_title:
        out += ["# Progress board", ""]
        out.append("Generated by `.github/workflows/board.yml`. "
                   "Do not edit by hand.")
        out.append("")

    if not records:
        out.append("_No results yet._")
        out.append("")
    else:
        # Сводка по трекам
        for track, lessons in TRACKS.items():
            done_map = {l: passed(records, track, l) for l in lessons}
            finished = [u for u in users
                        if all(u in done_map[l] for l in lessons)]
            out.append("## Track %s" % track)
            out.append("")
            out.append("Participants: **%d** · "
                       "finished the whole track: **%d**" % (len(users), len(finished)))
            out.append("")
            out.append("| Lesson | Passed | Progress |")
            out.append("|---|---|---|")
            for l in lessons:
                n = len(done_map[l])
                out.append("| %s | %d / %d | `%s` |"
                           % (LESSON_TITLES.get(l, l), n, len(users), bar(n, len(users))))
            out.append("")

        # Последние результаты
        out.append("## Latest results")
        out.append("")
        out.append("| When | Student | Lesson | Score | Lang |")
        out.append("|---|---|---|---|---|")
        for r in sorted(records, key=lambda r: r.get("ts", ""), reverse=True)[:50]:
            out.append("| %s | %s | %s | %d/%d | %s |"
                       % (r.get("ts", "")[:10].replace("-", "-") or "—",
                          r["user"], r["lesson"], r["pass"], r["total"], r["lang"]))
        out.append("")

    text = "\n".join(out).rstrip() + "\n"
    os.makedirs(os.path.dirname(BOARD_MD), exist_ok=True)
    with open(BOARD_MD, "w", encoding="utf-8") as f:
        f.write(text)
    print("board/board.md обновлён, записей: %d" % len(records))
    return text


def issue_body():
    """Тело issue: шапка + таблица между маркерами BOARD_START/BOARD_END."""
    base = ""
    if os.path.exists(ISSUE_BODY):
        with open(ISSUE_BODY, encoding="utf-8") as f:
            base = f.read()
    table = render(with_title=False)
    # Оставляем заголовки, таблицы, сводку и пустые строки — иначе таблицы
    # склеиваются в одну при отрисовке.
    keep = ("|", "#", "Participants", "_No results", "")
    table = "\n".join(l for l in table.splitlines()
                      if l.startswith(keep) or l == "")
    return "%s\n<!-- BOARD_START -->\n%s\n<!-- BOARD_END -->\n" % (
        base.rstrip(), table.strip())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["add", "render", "show", "issue-body"])
    ap.add_argument("--body", default="")
    args = ap.parse_args()

    if args.cmd == "add":
        rec = parse_marker(args.body)
        if add(rec):
            render()
        return 0
    if args.cmd == "render":
        render()
        return 0
    if args.cmd == "issue-body":
        sys.stdout.write(issue_body())
        return 0
    if args.cmd == "show":
        for r in load():
            print(r)
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
